server:
  port: 8083

spring:
  datasource:
    username: admin
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: rootroot
    realmImportFile: journal-de-bord-realm.json
